"""Public config API (``from cicerone.config import …``)."""

from __future__ import annotations

from cicerone.config.constants import (
    AUTOML_DEFAULT_N_SPLITS,
    AUTOML_DEFAULT_PRIMARY_METRIC,
    AUTOML_DEFAULT_TEST_DAYS,
    DEFAULT_CONFIG_PATH,
    DEFAULT_CONTENT_FALLBACK_MAX_NEIGHBORS,
    DEFAULT_EPOCH_METRICS_EVERY,
    DEFAULT_EPOCH_METRICS_MAX_USERS,
    DEFAULT_EPOCH_METRICS_PLATEAU_EPS,
    DEFAULT_EPOCH_METRICS_PLATEAU_WINDOW,
    DEFAULT_EPOCH_METRICS_REGRESSION_DROP,
    DEFAULT_EVENTS_BATCH_SIZE,
    DEFAULT_EVENTS_BATCH_WINDOW_SECONDS,
    DEFAULT_EVENTS_POLL_INTERVAL_SECONDS,
    DEFAULT_EVENTS_WEBHOOK_MAX_PENDING,
    DEFAULT_EXPLAIN_MAX_ATTRIBUTES,
    DEFAULT_EXPLAIN_MAX_SIMILAR_ITEMS,
    DEFAULT_ITEM_BASED_K_NEIGHBORS,
    DEFAULT_LOCK_KEY,
    DEFAULT_LOCK_TTL_SECONDS,
    DEFAULT_MAX_WORKERS,
    DEFAULT_SEQUENTIAL_MIN_MEDIAN_INTERACTIONS,
    LOCK_BACKENDS,
    MODES,
    STRATEGY_NAMES,
    ConfigError,
    Mode,
    StrategyName,
)
from cicerone.config.events import coerce_events_settings, load_events_settings
from cicerone.config.load import load_settings, make_settings
from cicerone.config.lock_url import (
    POSTGRES_LOCK_URL_REQUIRED,
    require_postgres_lock_url_parts,
    resolve_postgres_lock_url,
    resolve_postgres_lock_url_parts,
)
from cicerone.config.settings import (
    AutomlSettings,
    DashboardSettings,
    EpochMetricsSettings,
    EventsIncrementalSettings,
    EventsSettings,
    ExplainSettings,
    IOSettings,
    ServeSettings,
    Settings,
    TriggerSettings,
)
from cicerone.config.validation import (
    resolve_epoch_metrics,
    resolve_max_workers,
    validate_model_weights,
    validate_rrf_k,
)

__all__ = [
    "AUTOML_DEFAULT_N_SPLITS",
    "AUTOML_DEFAULT_PRIMARY_METRIC",
    "AUTOML_DEFAULT_TEST_DAYS",
    "AutomlSettings",
    "ConfigError",
    "DEFAULT_CONFIG_PATH",
    "DEFAULT_CONTENT_FALLBACK_MAX_NEIGHBORS",
    "DEFAULT_EPOCH_METRICS_EVERY",
    "DEFAULT_EPOCH_METRICS_MAX_USERS",
    "DEFAULT_EPOCH_METRICS_PLATEAU_EPS",
    "DEFAULT_EPOCH_METRICS_PLATEAU_WINDOW",
    "DEFAULT_EPOCH_METRICS_REGRESSION_DROP",
    "DEFAULT_EVENTS_BATCH_SIZE",
    "DEFAULT_EVENTS_BATCH_WINDOW_SECONDS",
    "DEFAULT_EVENTS_POLL_INTERVAL_SECONDS",
    "DEFAULT_EVENTS_WEBHOOK_MAX_PENDING",
    "DEFAULT_EXPLAIN_MAX_ATTRIBUTES",
    "DEFAULT_EXPLAIN_MAX_SIMILAR_ITEMS",
    "DEFAULT_ITEM_BASED_K_NEIGHBORS",
    "DEFAULT_LOCK_KEY",
    "DEFAULT_LOCK_TTL_SECONDS",
    "DEFAULT_MAX_WORKERS",
    "DEFAULT_SEQUENTIAL_MIN_MEDIAN_INTERACTIONS",
    "DashboardSettings",
    "EpochMetricsSettings",
    "EventsIncrementalSettings",
    "EventsSettings",
    "ExplainSettings",
    "IOSettings",
    "LOCK_BACKENDS",
    "MODES",
    "Mode",
    "POSTGRES_LOCK_URL_REQUIRED",
    "STRATEGY_NAMES",
    "ServeSettings",
    "Settings",
    "StrategyName",
    "TriggerSettings",
    "coerce_events_settings",
    "load_events_settings",
    "load_settings",
    "make_settings",
    "require_postgres_lock_url_parts",
    "resolve_epoch_metrics",
    "resolve_max_workers",
    "resolve_postgres_lock_url",
    "resolve_postgres_lock_url_parts",
    "validate_model_weights",
    "validate_rrf_k",
]
